var physics = pathgl.texture()

d3.select('canvas').call(pathgl)
.selectAll("circle")
.data(d3.range(100))
.enter().append("circle")
.attr('fill', function () { return "hsl(" + Math.random() * 360 + ",100%, 50%)" })
.attr('cx', function (d, i) { return Math.random() * 900 })
.attr('cy', function (d, i) { return Math.random() * 600 })
.attr('r', function (d, i) { return 5 })
